INCLPATH= -I ./
SRCPATH= ./
CC=gcc
CCOPT= -Wall -std=c99

all: jeu_de_la_vie_implementation.c jeu_de_la_vie_implementation.h
	$(CC) $(CCOPT) -o jeuDeLaVie jeu_de_la_vie_implementation.c $(INCLPATH)

clean : 
	rm jdv* jeuDeLaVie
