/*-  Generated by Multifor-compiler  - */
void calc_multifor (){
    int i, i2,j,j2;
    int _mfr_ref0; int _mfr_ref1; 
    if (N >= 3) {
        for (_mfr_ref0=0;_mfr_ref0<=min(2,N-3);_mfr_ref0++) {    
            for (_mfr_ref1=0;_mfr_ref1<=N-3;_mfr_ref1++) {    
                i=1+_mfr_ref0;
                j=1+_mfr_ref1;
                temp[i-1][j-1]=game_of_life(t[i][j],t[i-1][j],t[i-1][j-1],t[i-1][j+1],[i][j-1],[i][j+1],[i+1][j-1],[i+1][j],[i+1][j+1]);
            }
        }
        for (_mfr_ref0=3;_mfr_ref0<=N-3;_mfr_ref0++) {    
            for (_mfr_ref1=0;_mfr_ref1<=N-3;_mfr_ref1++) {    
                i=1+_mfr_ref0;
                j=1+_mfr_ref1;
                temp[i-1][j-1]=game_of_life(t[i][j],t[i-1][j],t[i-1][j-1],t[i-1][j+1],[i][j-1],[i][j+1],[i+1][j-1],[i+1][j],[i+1][j+1]);

                i2=1+(_mfr_ref0-3);
                j2=1+_mfr_ref1;
                t[i2][j2]=temp[i2-1][j2-1];

            }
        }
        for (_mfr_ref0=max(3,N-2);_mfr_ref0<=N;_mfr_ref0++) {    
            for (_mfr_ref1=0;_mfr_ref1<=N-3;_mfr_ref1++) {    
                i2=1+(_mfr_ref0-3);
                j2=1+_mfr_ref1;
                t[i2][j2]=temp[i2-1][j2-1];

            }
        }
    }
}
